apiVersion: v1
kind: Service
metadata:
  name: bookservice
spec:
  type: NodePort
  selector:
    app: bookservice
  ports:
    - protocol: TCP
      port: 80            # internal service port
      targetPort: 3000    # container port
      nodePort: 30082     # <-- change to a free port (30000-32767)
